allprojects {
    repositories {
        mavenCentral()
        maven {
            name = "MinecraftForge"
            url = "https://maven.minecraftforge.net/"
        }
        maven {
            name = "Illusive Soulworks Maven"
            url = "https://maven.theillusivec4.top/"
        }
        maven {
            name = "CurseMaven"
            url = "https://www.cursemaven.com"
        }
        maven {
            name = "Sponge"
            url = "https://repo.spongepowered.org/repository/maven-public/"
        }
    }
}